select * from USU_TCOPSAB;

select * from r008evc where codtab = 1 and codeve = 4354;

INSERT INTO R008EVC (CODTAB, CODEVE, EVEDPO, CODCLC, EVEDNE, CODSEL, SINSEL, VALCAL,
TIPINF, DIMNOR, VALTET, ALFAEV, CRTEVE, CODCRT, DESEVE, TIPEVE, NATEVE, RGRESP, HORUTI, 
RGREVE, RUBHOM, OBSEVE, ARRESP, REMPAT, INIVAL, USU_CODCGI, USU_GRUPEVT, FIMVAL, DESCOM, 
PEREVE, CODSIN, GEREVE, PRJEVE, RATEVE, ARRVAL, ARRPRE, TIPRAT, REMCAG) VALUES 
(1, 4354, 0, 109, 0, 0, ' ', 0.0, 'V', 'N', 0.0, ' ', '49F', 4906, 'Plano Saúde Teste', 
3, 0, 0, 'N', 45, 0, ' ', 0, 'N', '01/05/2021', 0, 7, '01/05/2030', ' ', 
' ', 0, 1, 'N', 'P', 0, 0, 0, 'N');

SELECT /*+ FIRST_ROWS */ R008VIN.CODTAB "CODTAB", R008VIN.CODEVE "CODEVE", 
R008VIN.CODVIN "CODVIN" FROM R008VIN WHERE R008VIN.CODTAB = ? AND R008VIN.CODEVE = ? 
AND R008VIN.CODVIN < ? ORDER BY 1 DESC, 2 DESC, 3 DESC;

select * from RTC_PENDENCIES;
select * from VETORH.RTC_R008EVC_I;

select * from 