--COLABORADORES COM CAMPO CODMOD = 17
SELECT 
MDL.NUMEMP,
MDL.TIPCOL,
MDL.NUMCAD,
FUN.NOMFUN,
MDL.CODMOD,
MDL.INDCON,
FUN.SITAFA

FROM R034MDL MDL, R034FUN FUN
WHERE 
MDL.NUMEMP = FUN.NUMEMP AND
MDL.TIPCOL = FUN.TIPCOL AND
MDL.NUMCAD = FUN.NUMCAD AND
MDL.NUMEMP = 1 AND 
MDL.TIPCOL = 1 AND 
MDL.CODMOD = 17 ;




--COLABORADORES ASSOCIADOS R034FUN E R034USU
SELECT 
USU.NUMEMP,
USU.TIPCOL,
USU.NUMCAD,
FUN.NOMFUN,
USU.CODUSU,
NUSU.NOMUSU,
CPL.EMAIL,
USU.CRIUSU,
FUN.SITAFA

FROM R034USU USU, R034FUN FUN, R999USU NUSU, R900CPL CPL 
WHERE 
USU.NUMEMP = FUN.NUMEMP AND
USU.TIPCOL = FUN.TIPCOL AND
USU.NUMCAD = FUN.NUMCAD AND
USU.CODUSU = NUSU.CODUSU AND
USU.CODUSU = CPL.PERID AND
NUSU.CODUSU = CPL.PERID AND
USU.NUMEMP = 1 AND 
USU.TIPCOL = 1 AND
FUN.SITAFA <> 7;

--COLABORADORES ATIVOS NA EMPRESA EM 24/09/21
select * from r034fun where sitafa = 1 and numemp = 1 and tipcol = 1;

--CODIGO DO MODULO PAINEL DE GESTÃO
SELECT * FROM R034MDL WHERE NUMEMP = 1 AND TIPCOL = 1 AND CODMOD = 17;

--Tabelas:
SELECT * FROM R999USU;
SELECT * FROM r900pdt;
SELECT * FROM r900ppl;
SELECT * FROM r900cpl;
SELECT * FROM r910ent;
SELECT * FROM r910usu;
SELECT * FROM r999usu;
SELECT * FROM r900grp;
SELECT * FROM r910mgp;

